workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/PizzasAndBeer.xcworkspace"
        XCODE_SCHEME: "PizzasAndBeer"
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Prebuild Expo (if using Managed Workflow)
        script: |
          npx expo prebuild
      - name: Build iOS App
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/build/PizzasAndBeer.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/PizzasAndBeer.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tuemail@example.com
