workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "ios/PizzasAndBeer.xcworkspace"
        XCODE_SCHEME: "PizzasAndBeer"
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install
      - name: Generate iOS project (expo prebuild)
        script: |
          npx expo prebuild --clean
          ls -la  # 🚨 Muestra el contenido del directorio después de prebuild
          if [ ! -d "ios" ]; then
            echo "❌ Error: La carpeta 'ios' no se generó correctamente"
            exit 1
          fi
          if [ ! -f "ios/PizzasAndBeer.xcworkspace" ]; then
            echo "❌ Error: 'PizzasAndBeer.xcworkspace' no se generó"
            exit 1
          fi
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS App
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $HOME/build/PizzasAndBeer.xcarchive
      - name: Export .ipa
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/PizzasAndBeer.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/build/ipa
    artifacts:
      - build/ipa/*.ipa
    publishing:
      email:
        recipients:
          - tuemail@example.com
